#!/bin/bash -l
#$ -cwd
#$ -S /bin/bash
#$ -V
#$ -q hp.q
#$ -l h_vmem=50G
#$ -l s_rt=10:00:00
#$ -pe smp 8
#$ -m a
#$ -M pzhou@caas.cn
#$ -j y
#$ -o job3.out
#$ -N shift

ncpu=8
cd $cg/src
source activate cage

Rscript --no-init-file --no-restore cg.job.03.R
